title: "嫦娥奔月"
author: "若兰"
createdDate: "2025-08-22"
tags: ["经典", "神话", "嫦娥"]

pages:
  - "很久很久以前，天上有十个火辣辣的太阳，把大地烤得焦干，庄稼枯萎，人们苦不堪言。"
  - "这时，一位名叫后羿的大英雄站了出来。他力大无穷，箭术高超，决心拯救苍生。"
  - "后羿搭弓射箭，只听“嗖嗖”几声，九个太阳应声而落。大地恢复了清凉，万物复苏，人们欢呼雀跃。"
  - "为了感谢后羿的功绩，西王母娘娘特意赐予他一颗仙丹。据说，吃了这颗仙丹就能立刻飞升成仙。"
  - "后羿深爱着美丽的妻子嫦娥，他不想一个人飞升离去。于是，他把仙丹小心翼翼地藏在了家里的宝盒中。"
  - "有一天，后羿外出狩猎，家里只剩下嫦娥一人。一个名叫蓬蒙的盗贼，早就觊觎后羿的仙丹，趁机偷偷潜入了后羿的家。"
  - "嫦娥听到了响动，发现蓬蒙正要打开藏着仙丹的宝盒。她心急如焚，担心仙丹落入坏人之手会危害人间。"
  - "在这危急关头，嫦娥来不及多想，为了保护仙丹不被恶人夺走，她毅然决然地将仙丹吞了下去。"
  - "仙丹一入口，嫦娥的身体变得轻盈起来，她缓缓地飘离地面，越飞越高，向着夜空中的月亮飞去。"
  - "从此，嫦娥便住在寂寞的月亮上，成为了美丽的月宫仙子。每当月圆之夜，人们都会仰望天空，思念着这位善良的仙子。"