title: 若兰和哪吒的暑假奇遇
author: 若兰
createdDate: '2025-08-25'
tags:
  - AI生成
  - 儿童故事
pages:
  - 暑假到了，小姑娘若兰背着小书包，开心地来到了表哥哪吒的家。哪吒早就等在门口，一看到若兰就高兴地跑过来，拉着她的手说：“若兰妹妹，你终于来啦！”
  - 第二天一早，哪吒就带着若兰去了家后面的大山。山里绿油油的，空气好清新！突然，一只白色的小兔子从草丛里跳出来，若兰和哪吒立刻兴奋地追了上去。
  - 小兔子跑得真快，一溜烟就不见了。若兰有点气喘吁吁，哪吒笑着说：“没关系，我们去池塘边玩吧！”他们来到一个开满了荷花的池塘，碧绿的荷叶像一把把小伞。
  - 哪吒小心地摘下几个大大的莲蓬，剥开给若兰吃，莲子又甜又脆。若兰也学着哪吒的样子，摘了一片大荷叶，顶在头上当帽子，哪吒见了也摘了一片，两人对视一眼，都忍不住笑了起来。
  - 玩累了，哪吒神秘地对若兰说：“若兰妹妹，你想去一个更特别的地方玩吗？一个你从来没去过的地方！”若兰好奇地眨了眨眼睛，点点头。
  - “跟我来！”哪吒拉着若兰的手，他们来到海边。哪吒念了几句咒语，海水就自动分开了一条路，露出了通往海底的台阶。若兰瞪大了眼睛，惊喜地跟着哪吒走了下去。
  - 哇！眼前是一个金碧辉煌的水晶宫殿！宫殿门口站着威武的虾兵和蟹将，他们穿着闪亮的盔甲，手持长矛，看到哪吒和若兰走过来，都恭敬地行礼。
  - 宫殿里，一位慈祥的龟丞相慢悠悠地游过来，他戴着一顶小帽子，背着厚厚的龟壳，笑眯眯地对他们说：“哪吒小英雄，欢迎欢迎，这位小姑娘是？”哪吒向龟丞相介绍了若兰。
  - 龟丞相带着他们继续往里走，穿过一道道珊瑚拱门，若兰突然看到一个巨大无比的东西，它高耸入云，一眼望不到头，粗壮得像一座山，还闪着耀眼的金光！
  - “这就是定海神针！”哪吒自豪地告诉若兰。若兰摸了摸冰凉的柱身，感觉自己像个小小的蚂蚁。这次龙宫之旅，真是若兰暑假里最难忘的冒险！
